/// Flutter icons AUMIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  AUMIcons
///      fonts:
///       - asset: fonts/AUMIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class AUMIcons {
  AUMIcons._();

  static const _kFontFam = 'AUMIcons';

  // ignore: constant_identifier_names
  static const IconData forbidden_alone_people = IconData(0xe800, fontFamily: _kFontFam);
  // ignore: constant_identifier_names
  static const IconData forbidden_babies = IconData(0xe801, fontFamily: _kFontFam);
  // ignore: constant_identifier_names
  static const IconData forbidden_cats = IconData(0xe802, fontFamily: _kFontFam);
  // ignore: constant_identifier_names
  static const IconData forbidden_dogs = IconData(0xe803, fontFamily: _kFontFam);
  // ignore: constant_identifier_names
  static const IconData forbidden_kids = IconData(0xe804, fontFamily: _kFontFam);
  // ignore: constant_identifier_names
  static const IconData forbidden_old_people = IconData(0xe805, fontFamily: _kFontFam);
  // ignore: constant_identifier_names
  static const IconData forbidden_outdoor = IconData(0xe806, fontFamily: _kFontFam);
  static const IconData identification = IconData(0xe807, fontFamily: _kFontFam);
  static const IconData kid = IconData(0xe808, fontFamily: _kFontFam);
  // ignore: constant_identifier_names
  static const IconData not_vaccinated = IconData(0xe809, fontFamily: _kFontFam);
  // ignore: constant_identifier_names
  static const IconData old_people = IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData outdoor = IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData people = IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData sterilized = IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData vaccination = IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData baby = IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData cat = IconData(0xe810, fontFamily: _kFontFam);
  static const IconData dog = IconData(0xe811, fontFamily: _kFontFam);
}
