/// Flutter icons AUMIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  AUMIcons
///      fonts:
///       - asset: fonts/AUMIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class AUMIcons {
  AUMIcons._();

  static const _kFontFam = 'AUMIcons';
  static const String? _kFontPkg = null;

  static const IconData forbiddenkids = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData forbiddenoldpeople = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData forbiddenoutdoor = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData identification = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData kid = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notvaccinated = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData outdoor = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData oldpeople = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData people = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sterilized = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData baby = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cat = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dog = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData forbiddencats = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData forbiddenalonepeople = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData forbiddenbabies = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData forbiddendogs = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vaccination = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData kitty = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
